//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoJSON.Net.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoJSON.Net.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;type&quot;: &quot;Feature&quot;,
        ///    &quot;geometry&quot;: {
        ///    &quot;type&quot;: &quot;Point&quot;,
        ///    &quot;coordinates&quot;: [102.0, 0.5]
        ///    },
        ///    &quot;properties&quot;: {
        ///    &quot;prop0&quot;: &quot;value0&quot;
        ///    }
        ///}.
        /// </summary>
        internal static string SampleFeature {
            get {
                return ResourceManager.GetString("SampleFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;FeatureCollection&quot;,
        ///  &quot;features&quot;: [
        ///    {
        ///      &quot;type&quot;: &quot;Feature&quot;,
        ///      &quot;geometry&quot;: {
        ///        &quot;type&quot;: &quot;Point&quot;,
        ///        &quot;coordinates&quot;: [102.0, 0.5]
        ///      },
        ///      &quot;properties&quot;: {
        ///        &quot;prop0&quot;: &quot;value0&quot;
        ///      }
        ///    },
        ///    {
        ///      &quot;type&quot;: &quot;Feature&quot;,
        ///      &quot;geometry&quot;: {
        ///        &quot;type&quot;: &quot;LineString&quot;,
        ///        &quot;coordinates&quot;: [
        ///          [102.0, 0.0], [103.0, 1.0], [104.0, 0.0], [105.0, 1.0]
        ///        ]
        ///      },
        ///      &quot;properties&quot;: {
        ///        &quot;prop1&quot;: 0.0,
        ///        &quot;prop0&quot;: &quot;valu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleFeatureCollection {
            get {
                return ResourceManager.GetString("SampleFeatureCollection", resourceCulture);
            }
        }
    }
}
